
export const DarkColors = [
    { id: 1,
    color: "#09090b", 
    theme: "Dark",
    style: "Background 1",
    },
    { id: 2,
    color: "#18181b", 
    theme: "Dark",
    style: "Background 2",
    },
    { id: 3,
    color: "#fff1f2", 
    theme: "Dark",
    style: "Heading",
    },
    { id: 4,
    color: "#a3a3a3", 
    theme: "Dark",
    style: "Paragraph",
    },

    { id: 5,
    color: "#52525b", 
    theme: "Dark",
    style: "Muted",
    },
    { id: 6,
    color: "#d4d4d4", 
    theme: "Dark",
    style: "Links",
    },
    { id: 7,
    color: "#27272a", 
    theme: "Dark",
    style: "Border",
    },
    { id: 8,
    color: "#27272a", 
    theme: "Dark",
    style: "Ring",
    },
    { id: 9,
    color: "#18181b", 
    theme: "Dark",
    style: "Card",
    },
];

export const LightColors = [
    { id: 1,
    color: "#fafafa", 
    theme: "Light",
    style: "Background 1",
    },
    { id: 2,
    color: "#f4f4f5", 
    theme: "Light",
    style: "Background 2",
    },
    { id: 3,
    color: "#4c0519", 
    theme: "Light",
    style: "Heading",
    },
    { id: 4,
    color: "#3f3f46", 
    theme: "Dark:",
    style: "Paragraph",
    },

    { id: 5,
    color: "#71717a", 
    theme: "Light",
    style: "Muted",
    },
    { id: 6,
    color: "#71717a", 
    theme: "Light",
    style: "Links",
    },
    { id: 7,
    color: "#e4e4e7", 
    theme: "Light",
    style: "Border",
    },
    { id: 8,
    color: "#e4e4e7", 
    theme: "Light",
    style: "Ring",
    },
    { id: 9,
    color: "#fff", 
    theme: "Light",
    style: "Card",
    },
];

// Primary Colors
export const PrimaryColors = [
    { id: 1,
      color: "#e11d48", 
      style: "Background 1",
    },
    { id: 2,
      color: "#f43f5e", 
      style: "Primary 2",
    },
  ];
  
  
  // Secondary Colors
  export const OtherColors = [
    { id: 1,
      color: "#17c964", 
      style: "Success",
    },
    { id: 2,
      color: "#f5a524", 
      style: "Warning",
    },
    { id: 3,
      color: "#f31260", 
      style: "Danger",
    },
  ];